// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_Image2;
void ui_event_xiaozhi(lv_event_t * e);
lv_obj_t * ui_xiaozhi;
void ui_event_Music(lv_event_t * e);
lv_obj_t * ui_Music;
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
void ui_event_Game(lv_event_t * e);
lv_obj_t * ui_Game;
void ui_event_Calendar(lv_event_t * e);
lv_obj_t * ui_Calendar;
void ui_event_Statement(lv_event_t * e);
lv_obj_t * ui_Statement;
void ui_event_Weather(lv_event_t * e);
lv_obj_t * ui_Weather;
void ui_event_SerialPort(lv_event_t * e);
lv_obj_t * ui_SerialPort;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_time;
lv_obj_t * ui_date;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_TextArea4;
// CUSTOM VARIABLES

// SCREEN: ui_xiaozhiPage
void ui_xiaozhiPage_screen_init(void);
lv_obj_t * ui_xiaozhiPage;
void ui_event_Image11(lv_event_t * e);
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_MusicPage
void ui_MusicPage_screen_init(void);
lv_obj_t * ui_MusicPage;
void ui_event_Image13(lv_event_t * e);
lv_obj_t * ui_Image13;
void ui_event_slidervolume(lv_event_t * e);
lv_obj_t * ui_slidervolume;
lv_obj_t * ui_Image14;
void ui_event_ddsonglist(lv_event_t * e);
lv_obj_t * ui_ddsonglist;
void ui_event_btnplaypause(lv_event_t * e);
lv_obj_t * ui_btnplaypause;
void ui_event_btnprev(lv_event_t * e);
lv_obj_t * ui_btnprev;
void ui_event_btnnext(lv_event_t * e);
lv_obj_t * ui_btnnext;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
lv_obj_t * ui_SettingsPage;
lv_obj_t * ui_Panel2;
void ui_event_Image15(lv_event_t * e);
lv_obj_t * ui_Image15;
lv_obj_t * ui_Image16;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Roller5;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// SCREEN: ui_GamePage
void ui_GamePage_screen_init(void);
lv_obj_t * ui_GamePage;
void ui_event_Image17(lv_event_t * e);
lv_obj_t * ui_Image17;
void ui_event_Image18(lv_event_t * e);
lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_CalendarPage
void ui_CalendarPage_screen_init(void);
lv_obj_t * ui_CalendarPage;
void ui_event_Image19(lv_event_t * e);
lv_obj_t * ui_Image19;
void ui_event_Calendar1(lv_event_t * e);
lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

// SCREEN: ui_StatementPage
void ui_StatementPage_screen_init(void);
lv_obj_t * ui_StatementPage;
void ui_event_Image20(lv_event_t * e);
lv_obj_t * ui_Image20;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
lv_obj_t * ui_WeatherPage;
void ui_event_Image21(lv_event_t * e);
lv_obj_t * ui_Image21;
lv_obj_t * ui_Roller6;
// CUSTOM VARIABLES

// SCREEN: ui_SerialPortPage
void ui_SerialPortPage_screen_init(void);
lv_obj_t * ui_SerialPortPage;
void ui_event_Image22(lv_event_t * e);
lv_obj_t * ui_Image22;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_TextArea3;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_xiaozhi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_xiaozhiPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_xiaozhiPage_screen_init);
    }
}

void ui_event_Music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MusicPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MusicPage_screen_init);
    }
}

void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsPage_screen_init);
    }
}

void ui_event_Game(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GamePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GamePage_screen_init);
    }
}

void ui_event_Calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalendarPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CalendarPage_screen_init);
    }
}

void ui_event_Statement(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StatementPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StatementPage_screen_init);
    }
}

void ui_event_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WeatherPage_screen_init);
    }
}

void ui_event_SerialPort(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SerialPortPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SerialPortPage_screen_init);
    }
}

void ui_event_Image11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_xiaozhi_cb(e);
    }
}

void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_slidervolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_volume_change(e);
    }
}

void ui_event_ddsonglist(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_song_select(e);
    }
}

void ui_event_btnplaypause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_play_pause(e);
    }
}

void ui_event_btnprev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_prev(e);
    }
}

void ui_event_btnnext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_next(e);
    }
}

void ui_event_Image15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        silder_brightness_cb(e);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Keyboard_Show(e);
    }
}

void ui_event_Image17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Image18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Game_yang(e);
    }
}

void ui_event_Image19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Calendar1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        calendar_update_real_time(e);
    }
}

void ui_event_Image20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Image21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Image22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Keyboard1_Show(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_xiaozhiPage_screen_init();
    ui_MusicPage_screen_init();
    ui_SettingsPage_screen_init();
    ui_GamePage_screen_init();
    ui_CalendarPage_screen_init();
    ui_StatementPage_screen_init();
    ui_WeatherPage_screen_init();
    ui_SerialPortPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
