// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Image2;
void ui_event_xiaozhi(lv_event_t * e);
extern lv_obj_t * ui_xiaozhi;
void ui_event_Music(lv_event_t * e);
extern lv_obj_t * ui_Music;
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
void ui_event_Game(lv_event_t * e);
extern lv_obj_t * ui_Game;
void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
void ui_event_Statement(lv_event_t * e);
extern lv_obj_t * ui_Statement;
void ui_event_Weather(lv_event_t * e);
extern lv_obj_t * ui_Weather;
void ui_event_SerialPort(lv_event_t * e);
extern lv_obj_t * ui_SerialPort;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TextArea4;
// CUSTOM VARIABLES

// SCREEN: ui_xiaozhiPage
void ui_xiaozhiPage_screen_init(void);
extern lv_obj_t * ui_xiaozhiPage;
void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_MusicPage
void ui_MusicPage_screen_init(void);
extern lv_obj_t * ui_MusicPage;
void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
void ui_event_slidervolume(lv_event_t * e);
extern lv_obj_t * ui_slidervolume;
extern lv_obj_t * ui_Image14;
void ui_event_ddsonglist(lv_event_t * e);
extern lv_obj_t * ui_ddsonglist;
void ui_event_btnplaypause(lv_event_t * e);
extern lv_obj_t * ui_btnplaypause;
void ui_event_btnprev(lv_event_t * e);
extern lv_obj_t * ui_btnprev;
void ui_event_btnnext(lv_event_t * e);
extern lv_obj_t * ui_btnnext;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
extern lv_obj_t * ui_SettingsPage;
extern lv_obj_t * ui_Panel2;
void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Roller5;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// SCREEN: ui_GamePage
void ui_GamePage_screen_init(void);
extern lv_obj_t * ui_GamePage;
void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
void ui_event_Image18(lv_event_t * e);
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_CalendarPage
void ui_CalendarPage_screen_init(void);
extern lv_obj_t * ui_CalendarPage;
void ui_event_Image19(lv_event_t * e);
extern lv_obj_t * ui_Image19;
void ui_event_Calendar1(lv_event_t * e);
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

// SCREEN: ui_StatementPage
void ui_StatementPage_screen_init(void);
extern lv_obj_t * ui_StatementPage;
void ui_event_Image20(lv_event_t * e);
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
extern lv_obj_t * ui_WeatherPage;
void ui_event_Image21(lv_event_t * e);
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Roller6;
// CUSTOM VARIABLES

// SCREEN: ui_SerialPortPage
void ui_SerialPortPage_screen_init(void);
extern lv_obj_t * ui_SerialPortPage;
void ui_event_Image22(lv_event_t * e);
extern lv_obj_t * ui_Image22;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_screen_png);    // assets/screen.png
LV_IMG_DECLARE(ui_img_1215322996);    // assets/小智.png
LV_IMG_DECLARE(ui_img_1413029994);    // assets/音乐.png
LV_IMG_DECLARE(ui_img_1887403499);    // assets/设置.png
LV_IMG_DECLARE(ui_img_1076951215);    // assets/游戏_填充.png
LV_IMG_DECLARE(ui_img_2138131786);    // assets/日历.png
LV_IMG_DECLARE(ui_img_1090684027);    // assets/声明.png
LV_IMG_DECLARE(ui_img_944254084);    // assets/天气.png
LV_IMG_DECLARE(ui_img_868640562);    // assets/串口.png
LV_IMG_DECLARE(ui_img_1609717271);    // assets/返回.png
LV_IMG_DECLARE(ui_img_1086441320);    // assets/声音.png
LV_IMG_DECLARE(ui_img_862951715);    // assets/上一首.png
LV_IMG_DECLARE(ui_img_853450402);    // assets/下一首.png
LV_IMG_DECLARE(ui_img_252039257);    // assets/亮度_o.png
LV_IMG_DECLARE(ui_img_618490499);    // assets/羊.png
LV_IMG_DECLARE(ui_img_728335879);    // assets/16寄件、发送.png
LV_IMG_DECLARE(ui_img_1938144871);    // assets/接收消息模板.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
