// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_CalendarPage);
    lv_img_set_src(ui_Image19, &ui_img_1609717271);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image19, 132);
    lv_obj_set_y(ui_Image19, -93);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_CalendarPage);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 312);
    lv_obj_set_height(ui_Calendar1, 183);
    lv_obj_set_x(ui_Calendar1, 0);
    lv_obj_set_y(ui_Calendar1, 24);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Calendar1, ui_event_Calendar1, LV_EVENT_ALL, NULL);

}
