// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_GamePage_screen_init(void)
{
    ui_GamePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GamePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_GamePage);
    lv_img_set_src(ui_Image17, &ui_img_1609717271);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image17, 132);
    lv_obj_set_y(ui_Image17, -93);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_GamePage);
    lv_img_set_src(ui_Image18, &ui_img_618490499);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 77
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image18, ui_event_Image18, LV_EVENT_ALL, NULL);

}
