// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image2, &ui_img_screen_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_Image2, -1);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_xiaozhi = lv_img_create(ui_Home);
    lv_img_set_src(ui_xiaozhi, &ui_img_1215322996);
    lv_obj_set_width(ui_xiaozhi, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_xiaozhi, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_xiaozhi, -117);
    lv_obj_set_y(ui_xiaozhi, 73);
    lv_obj_set_align(ui_xiaozhi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xiaozhi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_xiaozhi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Music = lv_img_create(ui_Home);
    lv_img_set_src(ui_Music, &ui_img_1413029994);
    lv_obj_set_width(ui_Music, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Music, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Music, -38);
    lv_obj_set_y(ui_Music, 73);
    lv_obj_set_align(ui_Music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Music, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settings = lv_img_create(ui_Home);
    lv_img_set_src(ui_Settings, &ui_img_1887403499);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Settings, 37);
    lv_obj_set_y(ui_Settings, 73);
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Game = lv_img_create(ui_Home);
    lv_img_set_src(ui_Game, &ui_img_1076951215);
    lv_obj_set_width(ui_Game, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Game, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Game, 34);
    lv_obj_set_y(ui_Game, -2);
    lv_obj_set_align(ui_Game, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Game, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar = lv_img_create(ui_Home);
    lv_img_set_src(ui_Calendar, &ui_img_2138131786);
    lv_obj_set_width(ui_Calendar, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Calendar, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Calendar, -41);
    lv_obj_set_y(ui_Calendar, -2);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Calendar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Statement = lv_img_create(ui_Home);
    lv_img_set_src(ui_Statement, &ui_img_1090684027);
    lv_obj_set_width(ui_Statement, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Statement, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Statement, 117);
    lv_obj_set_y(ui_Statement, 73);
    lv_obj_set_align(ui_Statement, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Statement, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Statement, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather = lv_img_create(ui_Home);
    lv_img_set_src(ui_Weather, &ui_img_944254084);
    lv_obj_set_width(ui_Weather, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Weather, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Weather, 117);
    lv_obj_set_y(ui_Weather, -2);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SerialPort = lv_img_create(ui_Home);
    lv_img_set_src(ui_SerialPort, &ui_img_868640562);
    lv_obj_set_width(ui_SerialPort, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_SerialPort, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_SerialPort, -116);
    lv_obj_set_y(ui_SerialPort, -2);
    lv_obj_set_align(ui_SerialPort, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SerialPort, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SerialPort, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Panel1, 317);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -82);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Home);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -58);
    lv_obj_set_y(ui_time, -90);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00:00");
    lv_obj_set_style_text_font(ui_time, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Home);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -56);
    lv_obj_set_y(ui_date, -58);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "0000/00/00");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -116);
    lv_obj_set_y(ui_Label3, 37);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "串口");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -41);
    lv_obj_set_y(ui_Label4, 37);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "日历");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 34);
    lv_obj_set_y(ui_Label5, 37);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "游戏");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 114);
    lv_obj_set_y(ui_Label6, 37);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "天气");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -117);
    lv_obj_set_y(ui_Label7, 110);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "小智");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -38);
    lv_obj_set_y(ui_Label8, 110);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "音乐");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 37);
    lv_obj_set_y(ui_Label9, 110);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "设置");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 117);
    lv_obj_set_y(ui_Label10, 110);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "声明");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_Home);
    lv_obj_set_width(ui_TextArea4, 101);
    lv_obj_set_height(ui_TextArea4, 60);
    lv_obj_set_x(ui_TextArea4, 95);
    lv_obj_set_y(ui_TextArea4, -84);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4, "wifi:未连接");
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_xiaozhi, ui_event_xiaozhi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Music, ui_event_Music, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Game, ui_event_Game, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Calendar, ui_event_Calendar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Statement, ui_event_Statement, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Weather, ui_event_Weather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SerialPort, ui_event_SerialPort, LV_EVENT_ALL, NULL);

}
