// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MusicPage_screen_init(void)
{
    ui_MusicPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MusicPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image13, &ui_img_1609717271);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image13, 133);
    lv_obj_set_y(ui_Image13, -94);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slidervolume = lv_slider_create(ui_MusicPage);
    lv_slider_set_value(ui_slidervolume, 60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slidervolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slidervolume, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_slidervolume, 181);
    lv_obj_set_height(ui_slidervolume, 27);
    lv_obj_set_x(ui_slidervolume, 6);
    lv_obj_set_y(ui_slidervolume, -93);
    lv_obj_set_align(ui_slidervolume, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slidervolume, lv_color_hex(0xDDA7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slidervolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slidervolume, lv_color_hex(0xF9E9E9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slidervolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slidervolume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slidervolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image14, &ui_img_1086441320);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image14, -119);
    lv_obj_set_y(ui_Image14, -90);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ddsonglist = lv_roller_create(ui_MusicPage);
    lv_obj_set_width(ui_ddsonglist, 297);
    lv_obj_set_height(ui_ddsonglist, 122);
    lv_obj_set_x(ui_ddsonglist, 0);
    lv_obj_set_y(ui_ddsonglist, -3);
    lv_obj_set_align(ui_ddsonglist, LV_ALIGN_CENTER);

    ui_btnplaypause = lv_switch_create(ui_MusicPage);
    lv_obj_set_width(ui_btnplaypause, 83);
    lv_obj_set_height(ui_btnplaypause, 30);
    lv_obj_set_x(ui_btnplaypause, 0);
    lv_obj_set_y(ui_btnplaypause, 88);
    lv_obj_set_align(ui_btnplaypause, LV_ALIGN_CENTER);

    ui_btnprev = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_btnprev, &ui_img_862951715);
    lv_obj_set_width(ui_btnprev, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_btnprev, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_btnprev, -88);
    lv_obj_set_y(ui_btnprev, 87);
    lv_obj_set_align(ui_btnprev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnprev, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnprev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnnext = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_btnnext, &ui_img_853450402);
    lv_obj_set_width(ui_btnnext, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_btnnext, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_btnnext, 94);
    lv_obj_set_y(ui_btnnext, 85);
    lv_obj_set_align(ui_btnnext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnnext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnnext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_slidervolume, ui_event_slidervolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddsonglist, ui_event_ddsonglist, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnplaypause, ui_event_btnplaypause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnprev, ui_event_btnprev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnnext, ui_event_btnnext, LV_EVENT_ALL, NULL);

}
