// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MusicPage_screen_init(void)
{
    ui_MusicPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MusicPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image13, &ui_img_1609717271);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image13, 133);
    lv_obj_set_y(ui_Image13, -94);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_MusicPage);
    lv_slider_set_value(ui_Slider1, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 181);
    lv_obj_set_height(ui_Slider1, 27);
    lv_obj_set_x(ui_Slider1, 6);
    lv_obj_set_y(ui_Slider1, -93);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xDDA7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xF9E9E9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image14, &ui_img_1086441320);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image14, -119);
    lv_obj_set_y(ui_Image14, -90);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller4 = lv_roller_create(ui_MusicPage);
    lv_roller_set_options(ui_Roller4, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller4, 139);
    lv_obj_set_height(ui_Roller4, 122);
    lv_obj_set_x(ui_Roller4, 0);
    lv_obj_set_y(ui_Roller4, -3);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_MusicPage);
    lv_obj_set_width(ui_Switch2, 60);
    lv_obj_set_height(ui_Switch2, 30);
    lv_obj_set_x(ui_Switch2, 0);
    lv_obj_set_y(ui_Switch2, 88);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Image3 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image3, &ui_img_862951715);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image3, -57);
    lv_obj_set_y(ui_Image3, 88);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_MusicPage);
    lv_img_set_src(ui_Image4, &ui_img_853450402);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image4, 59);
    lv_obj_set_y(ui_Image4, 88);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);

}
