// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingsPage_screen_init(void)
{
    ui_SettingsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_SettingsPage);
    lv_obj_set_width(ui_Panel2, 246);
    lv_obj_set_height(ui_Panel2, 52);
    lv_obj_set_x(ui_Panel2, -23);
    lv_obj_set_y(ui_Panel2, -87);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_SettingsPage);
    lv_img_set_src(ui_Image15, &ui_img_1609717271);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image15, 133);
    lv_obj_set_y(ui_Image15, -94);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_SettingsPage);
    lv_img_set_src(ui_Image16, &ui_img_252039257);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image16, -116);
    lv_obj_set_y(ui_Image16, -87);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_SettingsPage);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 171);
    lv_obj_set_height(ui_Slider2, 24);
    lv_obj_set_x(ui_Slider2, 8);
    lv_obj_set_y(ui_Slider2, -89);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xDDA7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xF9E9E9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_SettingsPage);
    lv_obj_set_width(ui_TextArea1, 310);
    lv_obj_set_height(ui_TextArea1, 43);
    lv_obj_set_x(ui_TextArea1, -1);
    lv_obj_set_y(ui_TextArea1, -31);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "请输入密码...");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller5 = lv_roller_create(ui_SettingsPage);
    lv_roller_set_options(ui_Roller5, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller5, 287);
    lv_obj_set_height(ui_Roller5, 108);
    lv_obj_set_x(ui_Roller5, 0);
    lv_obj_set_y(ui_Roller5, 49);
    lv_obj_set_align(ui_Roller5, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_SettingsPage);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 314);
    lv_obj_set_height(ui_Container1, 118);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 57);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_Container1);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 2);
    lv_obj_set_y(ui_Keyboard2, 1);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Image15, ui_event_Image15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea1);

}
