// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_StatementPage_screen_init(void)
{
    ui_StatementPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StatementPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_StatementPage);
    lv_img_set_src(ui_Image20, &ui_img_1609717271);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image20, 132);
    lv_obj_set_y(ui_Image20, -93);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_StatementPage);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 25);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11,
                      "这是一个关于「连接」的实验——让屏幕有\n了温度，让设备学会倾听。从一行代码到完\n整的智能终端，这是我对嵌入式世界的探索\n与热爱。\n\n\n	                                            —— LBY");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_StatementPage);
    lv_img_set_src(ui_Image3, &ui_img_1090684027);
    lv_obj_set_width(ui_Image3, 47);
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -74);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image20, ui_event_Image20, LV_EVENT_ALL, NULL);

}
