// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SerialPortPage_screen_init(void)
{
    ui_SerialPortPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SerialPortPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_SerialPortPage);
    lv_img_set_src(ui_Image22, &ui_img_1609717271);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image22, 134);
    lv_obj_set_y(ui_Image22, -92);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea2 = lv_textarea_create(ui_SerialPortPage);
    lv_obj_set_width(ui_TextArea2, 221);
    lv_obj_set_height(ui_TextArea2, 92);
    lv_obj_set_x(ui_TextArea2, -45);
    lv_obj_set_y(ui_TextArea2, -58);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_TextArea3 = lv_textarea_create(ui_SerialPortPage);
    lv_obj_set_width(ui_TextArea3, 221);
    lv_obj_set_height(ui_TextArea3, 92);
    lv_obj_set_x(ui_TextArea3, 42);
    lv_obj_set_y(ui_TextArea3, 64);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");

    ui_Image23 = lv_img_create(ui_SerialPortPage);
    lv_img_set_src(ui_Image23, &ui_img_728335879);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image23, 110);
    lv_obj_set_y(ui_Image23, -47);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_SerialPortPage);
    lv_img_set_src(ui_Image24, &ui_img_1938144871);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image24, -108);
    lv_obj_set_y(ui_Image24, 68);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_SerialPortPage);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 301);
    lv_obj_set_height(ui_Container2, 120);
    lv_obj_set_x(ui_Container2, -3);
    lv_obj_set_y(ui_Container2, 55);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Container2);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 5);
    lv_obj_set_y(ui_Keyboard1, -1);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Image22, ui_event_Image22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea2);

}
