// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WeatherPage_screen_init(void)
{
    ui_WeatherPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_WeatherPage);
    lv_img_set_src(ui_Image21, &ui_img_1609717271);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image21, 133);
    lv_obj_set_y(ui_Image21, -95);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller6 = lv_roller_create(ui_WeatherPage);
    lv_roller_set_options(ui_Roller6, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller6, 314);
    lv_obj_set_height(ui_Roller6, 178);
    lv_obj_set_x(ui_Roller6, 0);
    lv_obj_set_y(ui_Roller6, 25);
    lv_obj_set_align(ui_Roller6, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Image21, ui_event_Image21, LV_EVENT_ALL, NULL);

}
